src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\UserGroup", inversedBy="users")
     * @ORM\JoinTable(
     *  name="user_usergroup",
     *  joinColumns={
     *      @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="usergroup_id", referencedColumnName="id")
     *  }
     * )
     */
    private $userGroups;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $admin;

    public function __construct()
    {
        $this->userGroups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    /**
     * @return Collection|UserGroup[]
     */
    public function getUserGroups(): Collection
    {
        return $this->userGroups;
    }

    public function addUserGroup(UserGroup $userGroup): self
    {
        if (!$this->userGroups->contains($userGroup)) {
            $this->userGroups[] = $userGroup;
        }

        return $this;
    }

    public function removeUserGroup(UserGroup $userGroup): self
    {
        if ($this->userGroups->contains($userGroup)) {
            $this->userGroups->removeElement($userGroup);
        }

        return $this;
    }
    public function getRoles()
    {
        if($this->getAdmin()==true){
            return [
                'ROLE_ADMIN'
            ];
        }else{
            return [
                'ROLE_USER'
            ];
        }
    }
    public function getSalt() {}

    public function eraseCredentials() {}

    public function serialize()
    {
        return serialize([
            $this->id,
            $this->first_name,
            $this->last_name,
            $this->username,
            $this->password,
            $this->admin,
        ]);
    }

    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->first_name,
            $this->last_name,
            $this->username,
            $this->password,
            $this->admin,
            ) = unserialize($serialized, ['allowed_classes' => false ]);
    }

    public function __toString(): ?string
    {
        if($this->getAdmin()){
            return "Yes";
        }
        return "No";
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('username')
            ->add('password')
            ->add('admin');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\UserGroup;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    private $encoder;
    public function __construct(UserPasswordEncoderInterface $encoder)
    {
        $this->encoder = $encoder;
    }
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->remove('userGroups');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $plain_password = $user->getPassword();
            $user->setPassword(
                $this->encoder->encodePassword($user, $plain_password)
            );
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->remove('password');
        $form->remove('userGroups');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plain_password = $user->getPassword();
            $user->setPassword(
                $this->encoder->encodePassword($user, $plain_password)
            );
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
    /**
     * @Route("/{id}/user_groupadd", name="user_groupadd", methods={"GET","POST"})
     */
    public function user_groupadd(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $em = $this->getDoctrine()->getManager();
        $userGroups[]=$em->getRepository(UserGroup::class)->findGroupsNotJoined($user->getId());
        $form->handleRequest($request);

        if($request->isMethod('post')){
            $group_id = $request->request->get('_group');
            $group = $em->getRepository(UserGroup::class)->find($group_id);
            $user->getUserGroups()->add($group);
            $em->persist($group);
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/useraddgroup.html.twig', [
            'user'=>$user,
            'userGroups' => $userGroups,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/user_groupremove", name="user_groupremove", methods={"GET","POST"})
     */
    public function user_groupremove(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $em = $this->getDoctrine()->getManager();
        $userGroups[]=$em->getRepository(UserGroup::class)->findGroupsJoined($user->getId());

        $form->handleRequest($request);

        if($request->isMethod('post')){
            $data = $request->request;
            var_dump($data);
            exit(0);
            $group_id = $request->request->get('_group');
            $group = $em->getRepository(UserGroup::class)->find($group_id);
            $user->removeUserGroup($group);
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/userremovegroup.html.twig', [
            'user'=>$user,
            'userGroups' => $userGroups,
            'form' => $form->createView(),
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .error {color: #AA3333}
</style>
<div class="example-wrapper">
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        .error {color: #AA3333}
    </style>
<div class="example-wrapper">
    <h1>Users</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Username</th>
                <th>Admin</th>
                <th>Action</th>
                <th>UserGroup</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.admin ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
                <td>
                    <a href="{{ path('user_groupadd', {'id': user.id}) }}">Add</a>
                    <a href="{{ path('user_groupremove', {'id': user.id}) }}">Remove</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
</div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        .error {color: #AA3333}
    </style>
<div class="example-wrapper">
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .error {color: #AA3333}
</style>
<div class="example-wrapper">
    <h1>View User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>First Name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Admin</th>
                <td>{{ user.admin ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/user/useraddgroup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add User to Group{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .error {color: #AA3333}
</style>
<div class="example-wrapper">
    <h1>Add User to Group</h1>

    {% if userGroups[0] is empty %}
        <p class="error">There are no additional groups to add. </p>
    {% else %}
    <form action="{{ path('user_groupadd',{'id':user.id}) }}" method="post">
        <select class="form-control" id="grouplist" name="_group">
            {% for userGroup in userGroups[0] %}
            <option value='{{userGroup.id}}'>{{userGroup.name}}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn" >Submit</button>
    </form>
    {% endif %}

    <a href="{{ path('user_index') }}">back to list</a>
</div>
{% endblock %}

templates/user/userremovegroup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add User to Group{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        .error {color: #AA3333}
    </style>
    <div class="example-wrapper">
        <h1>Remove User from Group</h1>

        {% if userGroups[0] is empty %}
            <p class="error">User has not been added to any group</p>
        {% else %}
        <form action="{{ path('user_groupremove',{'id':user.id}) }}" method="post">
            <select class="form-control" id="grouplist" name="_group">
                {% for userGroup in userGroups[0] %}
                    <option value='{{userGroup.id}}'>{{userGroup.name}}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn">Submit</button>
        </form>
        {% endif %}

        <a href="{{ path('user_index') }}">back to list</a>
    </div>
{% endblock %}